from datetime import datetime, timedelta, timezone
from logging import Logger
from typing import Optional

import anduril.entitymanager.v1
import anduril.ontology.v1
import anduril.type
from anduril.entitymanager.v1 import (
    EntityManagerApiStub,
    GetEntityRequest,
    Entity,
    GetEntityResponse,
    PublishEntityResponse,
)
from grpclib.client import Channel

from ais import VesselData

EXPIRY_OFFSET_SECONDS = 10


class Lattice:
    def __init__(self, logger: Logger, lattice_ip: str, bearer_token: str):
        self.logger = logger
        self.lattice_ip = lattice_ip
        self.generated_metadata = {"authorization": "Bearer " + bearer_token}

    async def get_entity(self, entity_id) -> Optional[GetEntityResponse]:
        """
        Asynchronously retrieves an entity from the Lattice API using the provided entity ID.
        Usable wrapper around the get_entity API.
        For more information about this API, please refer to https://docs.anduril.com/sdks/python

        Args:
            entity_id (str): The ID of the entity to retrieve.

        Returns:
            Optional[GetEntityResponse]: The retrieved encased, or None if an error occurred.

        Raises:
            None

        """
        channel = Channel(host=self.lattice_ip, port=443, ssl=True)
        entity_manager_stub = EntityManagerApiStub(channel)

        try:
            response = await entity_manager_stub.get_entity(
                GetEntityRequest(entity_id=entity_id), metadata=self.generated_metadata
            )
            channel.close()
            return response
        except Exception as error:
            self.logger.error(f"lattice api get entity error {error}")
            channel.close()
            return None

    async def publish_entity(self, entity) -> Optional[PublishEntityResponse]:
        """
        Asynchronously publishes an entity to the Lattice API.
        Usable wrapper around the publish_entity API.
        For more information about this API, please refer to https://docs.anduril.com/entity/publishing-your-first-entity

        Args:
            entity (Entity): The entity to be published.

        Returns:
            Optional[PublishEntityResponse]: The response from the Lattice API, or None if an error occurred.

        Raises:
            None
        """
        channel = Channel(host=self.lattice_ip, port=443, ssl=True)
        entity_manager_stub = EntityManagerApiStub(channel)

        try:
            response = await entity_manager_stub.publish_entity(
                anduril.entitymanager.v1.PublishEntityRequest(entity=entity),
                metadata=self.generated_metadata,
            )
            channel.close()
            return response
        except Exception as error:
            self.logger.error(f"lattice api publish entity error {error}")
            channel.close()
            return None

    @staticmethod
    def generate_new_entity(vessel_data: VesselData) -> Entity:
        """
        Generates a new entity using the provided VesselData.

        For more information about these data fields, please refer to
        https://docs.anduril.com/reference/models/entitymanager/v1/entity

        Args:
            vessel_data (VesselData): The data containing relevant information about the vessel.

        Returns:
            Entity: The generated entity with the basic attributes filled out:
                - entity_id: The vessel's MMSI (blank if not provided).
                - description: A description of the vessel.
                - is_live: A boolean indicating whether the entity is live.
                - created_time: The time the entity was created.
                - expiry_time: The time the entity expires.
                - aliases: The aliases for the entity, including the vessel's MMSI.
                - mil_view: The military view for the entity.
                - location: The location of the entity, including latitude, longitude, and altitude.
                - ontology: The ontology for the entity, including the template, platform type, and specific type.
                - provenance: The provenance for the entity, including the data type, integration name, and source update time.
                - data_classification: The data classification for the entity, including the level of classification.
        """

        return Entity(
            entity_id=f"{vessel_data.MMSI}",  # Leaving this blank will generate an entityId
            description="Generated by AIS Vessel Traffic Dataset",
            is_live=True,
            created_time=datetime.now(timezone.utc),
            expiry_time=datetime.now(timezone.utc)
            + timedelta(seconds=EXPIRY_OFFSET_SECONDS),
            aliases=anduril.entitymanager.v1.Aliases(
                name=vessel_data.VesselName,
                alternate_ids=[
                    anduril.entitymanager.v1.AlternateId(
                        id=str(vessel_data.MMSI),
                        type=anduril.entitymanager.v1.AltIdType.MMSI_ID,
                    )
                ],
            ),
            mil_view=anduril.entitymanager.v1.MilView(
                disposition=anduril.ontology.v1.Disposition.NEUTRAL,
                environment=anduril.ontology.v1.Environment.SURFACE,
            ),
            location=anduril.entitymanager.v1.Location(
                position=anduril.entitymanager.v1.Position(
                    latitude_degrees=vessel_data.LAT,
                    longitude_degrees=vessel_data.LON,
                ),
            ),
            ontology=anduril.entitymanager.v1.Ontology(
                template=anduril.entitymanager.v1.Template.TRACK,
                # For more information, please refer to https://docs.anduril.com/entity/publishing-your-first-entity#define-ontology
                platform_type="Surface_Vessel",
            ),
            provenance=anduril.entitymanager.v1.Provenance(
                data_type="vessel-data",
                integration_name="ais-sample-integration",
                source_update_time=datetime.now(timezone.utc),
            ),
            data_classification=anduril.entitymanager.v1.Classification(
                default=anduril.entitymanager.v1.ClassificationInformation(
                    level=anduril.entitymanager.v1.ClassificationLevels.UNCLASSIFIED,
                )
            ),
        )
